openapi: 3.0.0
info:
  title: Swing Notes API
  version: 1.0.0
  description: Ett API för att hantera anteckningar

servers:
  - url: http://localhost:5050

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Note:
      type: object
      properties:
        title:
          type: string
          maxLength: 50
        text:
          type: string
          maxLength: 300

security:
  - bearerAuth: []

paths:
  /api/user/signup:
    post:
      summary: Skapa ett nytt konto
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: Användare skapad
        400:
          description: Användaren finns redan
        500:
          description: Serverfel

  /api/user/login:
    post:
      summary: Logga in och få JWT-token
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Inloggning lyckades
        401:
          description: Ogiltiga inloggningsuppgifter
        500:
          description: Serverfel

  /api/notes:
    get:
      summary: Hämta anteckningar för inloggad användare
      tags: [Notes]
      responses:
        200:
          description: Anteckningar hämtade
        500:
          description: Serverfel
    post:
      summary: Skapa ny anteckning
      tags: [Notes]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        201:
          description: Anteckning skapad
        400:
          description: Titel och text måste anges
        500:
          description: Serverfel

  /api/notes/{id}:
    put:
      summary: Uppdatera anteckning
      tags: [Notes]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        200:
          description: Anteckning uppdaterad
        400:
          description: Saknar titel/text
        404:
          description: Anteckning hittades inte
        500:
          description: Serverfel

    delete:
      summary: Radera anteckning
      tags: [Notes]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Anteckning borttagen
        404:
          description: Anteckning hittades inte
        500:
          description: Serverfel

  /api/notes/search:
    get:
      summary: Sök anteckningar på titel
      tags: [Notes]
      parameters:
        - in: query
          name: title
          required: true
          schema:
            type: string
      responses:
        200:
          description: Sökresultat
        400:
          description: Ingen sökterm angiven
        500:
          description: Serverfel